# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todolist.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todolist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etodolist.proto\"y\n\x12\x44\x65viceAnnouncement\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.DeviceType\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x13\n\x0bis_actuator\x18\x05 \x01(\x08\"<\n\nSensorData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x0c\n\x04unit\x18\x03 \x01(\t\"3\n\x0f\x41\x63tuatorCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x08\"%\n\x10GatewayDiscovery\x12\x11\n\tdata_port\x18\x01 \x01(\x05\"\xc3\x01\n\x10SmartCityMessage\x12+\n\x0c\x61nnouncement\x18\x01 \x01(\x0b\x32\x13.DeviceAnnouncementH\x00\x12\"\n\x0bsensor_data\x18\x02 \x01(\x0b\x32\x0b.SensorDataH\x00\x12#\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x10.ActuatorCommandH\x00\x12.\n\x11gateway_discovery\x18\x04 \x01(\x0b\x32\x11.GatewayDiscoveryH\x00\x42\t\n\x07payload*w\n\nDeviceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x43\x41MERA\x10\x01\x12\r\n\tLAMP_POST\x10\x02\x12\x11\n\rTRAFFIC_LIGHT\x10\x03\x12\x16\n\x12\x41IR_QUALITY_SENSOR\x10\x04\x12\x16\n\x12TEMPERATURE_SENSOR\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todolist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICETYPE']._serialized_start=493
  _globals['_DEVICETYPE']._serialized_end=612
  _globals['_DEVICEANNOUNCEMENT']._serialized_start=18
  _globals['_DEVICEANNOUNCEMENT']._serialized_end=139
  _globals['_SENSORDATA']._serialized_start=141
  _globals['_SENSORDATA']._serialized_end=201
  _globals['_ACTUATORCOMMAND']._serialized_start=203
  _globals['_ACTUATORCOMMAND']._serialized_end=254
  _globals['_GATEWAYDISCOVERY']._serialized_start=256
  _globals['_GATEWAYDISCOVERY']._serialized_end=293
  _globals['_SMARTCITYMESSAGE']._serialized_start=296
  _globals['_SMARTCITYMESSAGE']._serialized_end=491
# @@protoc_insertion_point(module_scope)
